#!/bin/zsh
export FOUNDRY_DISABLE_NIGHTLY_WARNING=true

# rpcs
geth_rpc="http://127.0.0.1:8545"
blade_rpc="http://127.0.0.1:10002"

# keys
priv_key="342605fcc263dd89b9ac7d975a4eb084b5ab6f6113dd278a8442ac4a8a8223f7"
pub_key="0xdb74B1a3f34D8a20a99B2d5A52e67697e951fd99"

# contracts
native_erc20="0x0000000000000000000000000000000000000106"

erc20_pred=$(cat genesis.json | grep internalERC20PredicateAddr | sed -E 's/.*"internalERC20PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')
erc20_mint_pred=$(cat genesis.json | grep internalMintableERC20PredicateAddr | sed -E 's/.*"internalMintableERC20PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')

erc721_pred=$(cat genesis.json | grep internalERC721PredicateAddr | sed -E 's/.*"internalERC721PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')
erc721_mint_pred=$(cat genesis.json | grep internalMintableERC721PredicateAddr | sed -E 's/.*"internalMintableERC721PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')

ext_erc20_pred=$(cat genesis.json | grep externalERC20PredicateAddr | sed -E 's/.*"externalERC20PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')
ext_mint_erc20_pred=$(cat genesis.json | grep externalMintableERC20PredicateAddr | sed -E 's/.*"externalMintableERC20PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')

ext_erc721_pred=$(cat genesis.json | grep externalERC721PredicateAddr | sed -E 's/.*"externalERC721PredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')
ext_mint_erc721_pred=$(cat genesis.json | grep externalERC721MintablePredicateAddr | sed -E 's/.*"externalERC721MintablePredicateAddress": "(0x[0-9a-fA-F]+)".*/\1/')

# functions
approve_func="function approve(address,uint256)"
deposit_func="function deposit(address,uint256)"
withdraw_func="function withdraw(address,uint256)"
src2dest="sourceTokenToDestinationToken(address)(address)"
balance_of="function balanceOf(address)(uint256)"
mint_func="function mint(address,uint256)(bool)"
set_approval_for_all="function setApprovalForAll(address,bool)(bool)"
mint_nft_func="function mint(address)"

# events
result_event_sig=0xc291164f30f10fd321c213fe9e048d68a831508af3aa2616356f843d1e06036d

# codes
mock_erc20="contracts/mocks/MockERC20.sol:MockERC20"
ext_mock_erc20_addr=""

mock_erc721="contracts/mocks/MockERC721.sol:MockERC721"
mock_erc721_addr=""
ext_mock_erc721_addr=""

# amounts
one_eth=1000000000000000000000000 # amount in wei, 1 ETH
half_eth=500000000000000000000000 # amount in wei, 0.5 ETH

# nft
nft_token_id=0
# nft_token_id=1
nft_token_id2=1

function addresses {
    echo
    info "Geth RPC: $geth_rpc"
    info "Blade RPC: $blade_rpc"
    info "Private key: $priv_key"
    info "Public key: $pub_key"
    info "Internal mintable ERC20 predicate: $erc20_mint_pred"
    info "Internal ERC20 predicate: $erc20_pred"
    info "Internal mintable ERC721 predicate: $erc721_mint_pred"
    info "Internal ERC721 predicate: $erc721_pred"
    info "External ERC20 predicate: $ext_erc20_pred"
    info "External mintable ERC20 predicate: $ext_mint_erc20_pred"
    info "External ERC721 predicate: $ext_erc721_pred"
    info "External mintable ERC721 predicate: $ext_mint_erc721_pred"
    info "Native ERC20: $native_erc20"
    info "Mock ERC721: $mock_erc721_addr"
    info "External Mock ERC20: $ext_mock_erc20_addr"
    info "External Mock ERC721: $ext_mock_erc721_addr"
}

# colors
RED="\033[31m"
GREEN="\033[32m"
BLUE="\033[34m"
RESET="\033[0m" 

function success {
    echo "${GREEN}$1${RESET}"
}

function error {
    echo "${RED}$1${RESET}"
}

function info {
    echo "${BLUE}$1${RESET}"
}

trap handleSigInt SIGINT

function handleSigInt() {
    echo "For quitting use command"
}

function mock_everything {
    cd blade-contracts
    ext_mock_erc20_addr=$(forge create --private-key $priv_key --rpc-url $geth_rpc $mock_erc20 --broadcast | grep Deployed | sed -e 's/Deployed to: //')
    mock_erc721_addr=$(forge create --private-key $priv_key --rpc-url $blade_rpc $mock_erc721 --broadcast | grep Deployed | sed -e 's/Deployed to: //')
    ext_mock_erc721_addr=$(forge create --private-key $priv_key --rpc-url $geth_rpc $mock_erc721 --broadcast | grep Deployed | sed -e 's/Deployed to: //')
    success "Everything mocked"
    info "Native ERC20: $native_erc20"
    info "Mock ERC721: $mock_erc721_addr"
    info "External Mock ERC20: $ext_mock_erc20_addr"
    info "External Mock ERC721: $ext_mock_erc721_addr"
    cd ..
}
mock_everything

# Mock ERC20 contract:
function create_mock_erc20 {
    cd blade-contracts
    ext_mock_erc20_addr=$(forge create --private-key $priv_key --rpc-url $geth_rpc $mock_erc20 --broadcast | grep Deployed | sed -e 's/Deployed to: //')
    success "Mock ERC20 contract address: $ext_mock_erc20_addr"
    cd ..
}

# Mock ERC721 contract:
function create_mock_erc721 {
    cd blade-contracts
    if [[ $1 == "i" ]]; then
        mock_erc721_addr=$(forge create --private-key $priv_key --rpc-url $blade_rpc $mock_erc721 --broadcast | grep Deployed | sed -e 's/Deployed to: //')
        success "Mock ERC721 contract address: $mock_erc721_addr"
        cd ..
        return
    fi

    ext_mock_erc721_addr=$(forge create --private-key $priv_key --rpc-url $geth_rpc $mock_erc721 --broadcast | grep Deployed | sed -e 's/Deployed to: //')
    success "External mock ERC721 contract address: $ext_mock_erc721_addr"
    cd ..
}

# Approve ERC20 contract:
function approve_erc20 {
    info "Approving ERC20 contract..."
    if [[ $1 == "i" ]]; then
        info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$native_erc20 \$approve_func \$erc20_mint_pred \$one_eth"
        echo

        cast send --private-key $priv_key --rpc-url $blade_rpc $native_erc20 $approve_func $erc20_mint_pred $one_eth | grep status
        return
    elif [[ $ext_mock_erc20_addr == "" ]]; then
        error "Mock ERC20 contract not created"
        return
    fi

    info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$mock_erc20_addr \$approve_func \$ext_erc20_pred \$one_eth"
    echo

    cast send --private-key $priv_key --rpc-url $geth_rpc $ext_mock_erc20_addr $approve_func $ext_erc20_pred $one_eth | grep status
}

# Approve ERC721 contract:
function approve_erc721 {
    info "Approving ERC721 contract..."
    if [[ $1 == "i" ]]; then
        if [[ $mock_erc721_addr == "" ]]; then
            error "Internal mock ERC721 contract not created"
            return
        fi
        # mint
        info "Minting before approve..."
        info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$mock_erc721_addr \$mint_nft_func \$pub_key "
        cast send --private-key $priv_key --rpc-url $blade_rpc $mock_erc721_addr $mint_nft_func $pub_key | grep status

        info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$mock_erc721_addr \$set_approval_for_all \$erc721_mint_pred true"
        cast send --private-key $priv_key --rpc-url $blade_rpc $mock_erc721_addr $set_approval_for_all $erc721_mint_pred true | grep status
       
        return
    fi

    if [[ $ext_mock_erc721_addr == "" ]]; then
        error "External mock ERC721 contract not created"
        return
    fi

    # mint
    info "Minting before approve..."
    info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$ext_mock_erc721_addr \$mint_nft_func \$pub_key"
    cast send --private-key $priv_key --rpc-url $geth_rpc $ext_mock_erc721_addr $mint_nft_func $pub_key | grep status

    info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$ext_mock_erc721_addr \$set_approval_for_all \$ext_mint_erc721_pred true"
    cast send --private-key $priv_key --rpc-url $geth_rpc $ext_mock_erc721_addr $set_approval_for_all $ext_erc721_pred true | grep status
}

# Deposit ERC20 contract:
function deposit_erc20 {
    info "Depositing ERC20 contract..."
    if [[ $1 == "i" ]]; then
        info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$native_erc20 \$deposit_func \$erc20_pred \$half_eth"

        cast send --private-key $priv_key --rpc-url $blade_rpc $erc20_mint_pred $deposit_func $native_erc20 $half_eth | grep status
        return
    elif [[ $ext_mock_erc20_addr == "" ]]; then
        error "Mock ERC20 contract not created"
        return
    fi

    info "Minting before depositing..."
    info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$mock_erc20_addr \$mint_func \$pub_key \$half_eth"
    echo

    # mint
    cast send --private-key $priv_key --rpc-url $geth_rpc $ext_mock_erc20_addr $mint_func $pub_key $half_eth | grep status

    info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$ext_erc20_pred \$deposit_func \$mock_erc20_addr \$half_eth"
    echo

    cast send --private-key $priv_key --rpc-url $geth_rpc $ext_erc20_pred $deposit_func $ext_mock_erc20_addr $half_eth | grep status
}

function deposit_erc721 {
    info "Depositing ERC721 contract..."
    if [[ $1 == "i" ]]; then
        if [[ $mock_erc721_addr == "" ]]; then
            error "Internal mock ERC721 contract not created"
            return
        fi

        info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$erc721_mint_pred \$deposit_func \$mock_erc721_addr \$nft_token_id"
        cast send --private-key $priv_key --rpc-url $blade_rpc $erc721_mint_pred $deposit_func $mock_erc721_addr $nft_token_id | grep status
        return
    fi

    if [[ $ext_mock_erc721_addr == "" ]]; then
        error "External mock ERC721 contract not created"
        return
    fi

    info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$ext_erc721_pred \$deposit_func \$ext_mock_erc721_addr \$nft_token_id"

    cast send --private-key $priv_key --rpc-url $geth_rpc $ext_erc721_pred $deposit_func $ext_mock_erc721_addr $nft_token_id | grep status
}

# Check ERC20 balance on external contract:
function check_balance_erc20 {
    info "Checking ERC20 balance..."
    if [[ $1 == "i" ]]; then
        external_token_addr=$(cast call $erc20_mint_pred --rpc-url $blade_rpc $src2dest $native_erc20)    
        success "External token address: $external_token_addr"

        info "RUN: cast call \$external_token_addr --rpc-url \$geth_rpc \$balance_of \$pub_key"
        cast call $external_token_addr --rpc-url $geth_rpc $balance_of $pub_key
        return
    elif [[ $ext_mock_erc20_addr == "" ]]; then
        error "Mock ERC20 contract not created"
        return
    fi

    internal_token_addr=$(cast call $ext_erc20_pred --rpc-url $geth_rpc $src2dest $ext_mock_erc20_addr)    
    success "Internal token address: $internal_token_addr"

    info "RUN: cast call \$internal_token_addr --rpc-url \$blade_rpc \$balance_of \$pub_key"
    cast call $internal_token_addr --rpc-url $blade_rpc $balance_of $pub_key
}

# Check ERC721 balance on external contract:
function check_balance_erc721 {
    info "Checking ERC721 balance..."
    if [[ $1 == "i" ]]; then
        if [[ $mock_erc721_addr == "" ]]; then
            error "Internal mock ERC721 contract not created"
            return
        fi

        external_token_addr=$(cast call $erc721_mint_pred --rpc-url $blade_rpc $src2dest $mock_erc721_addr)    
        success "External token address: $external_token_addr"

        info "RUN: cast call \$external_token_addr --rpc-url \$geth_rpc \$balance_of \$pub_key"
        cast call $external_token_addr --rpc-url $geth_rpc $balance_of $pub_key
        return
    fi

    if [[ $ext_mock_erc721_addr == "" ]]; then
        error "External mock ERC721 contract not created"
        return
    fi


    external_token_addr=$(cast call $ext_erc721_pred --rpc-url $geth_rpc $src2dest $ext_mock_erc721_addr)    
    success "External token address: $external_token_addr"

    info "RUN: cast call \$external_token_addr --rpc-url \$blade_rpc \$balance_of \$pub_key"
    cast call $external_token_addr --rpc-url $blade_rpc $balance_of $pub_key
}

function check_balance_local_erc20 {
    info "Checking ERC20 balance..."
    if [[ $1 == "i" ]]; then
        info "RUN: cast call \$native_erc20 --rpc-url \$blade_rpc \$balance_of \$pub_key"
        cast call $native_erc20 --rpc-url $blade_rpc $balance_of $pub_key
        return
    elif [[ $ext_mock_erc20_addr == "" ]]; then
        error "Mock ERC20 contract not created"
        return
    fi


    info "RUN: cast call \$mock_erc20_addr --rpc-url \$geth_rpc \$balance_of \$pub_key"
    cast call $ext_mock_erc20_addr --rpc-url $geth_rpc $balance_of $pub_key
}

function check_balance_local_erc721 {
    info "Checking ERC20 balance..."
    if [[ $1 == "i" ]]; then
    if [[ $mock_erc721_addr == "" ]]; then
            error "Internal mock ERC721 contract not created"
            return
        fi

        info "RUN: cast call \$mock_erc721_addr --rpc-url \$blade_rpc \$balance_of \$pub_key"
        cast call $mock_erc721_addr --rpc-url $blade_rpc $balance_of $pub_key
        return
    elif [[ $ext_mock_erc721_addr == "" ]]; then
        error "Mock ERC20 contract not created"
        return
    fi


    info "RUN: cast call \$mock_erc20_addr --rpc-url \$geth_rpc \$balance_of \$pub_key"
    cast call $ext_mock_erc721_addr --rpc-url $geth_rpc $balance_of $pub_key
}

# Withdraw ERC20 contract:
function withdraw_erc20 {
    info "Withdrawing ERC20 contract..."
    if [[ $1 == "i" ]]; then
        external_token_addr=$(cast call $erc20_mint_pred --rpc-url $blade_rpc $src2dest $native_erc20)    
        success "External token address: $external_token_addr"

        info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$ext_mint_erc20_pred \$withdraw_func \$external_token_addr \$half_eth "
        cast send --private-key $priv_key --rpc-url $geth_rpc $ext_mint_erc20_pred $withdraw_func $external_token_addr $half_eth | grep status
        return
    elif [[ $ext_mock_erc20_addr == "" ]]; then
        error "Mock ERC20 contract not created"
        return
    fi

    internal_token_addr=$(cast call $ext_erc20_pred --rpc-url $geth_rpc $src2dest $ext_mock_erc20_addr)
    success "Internal token address: $internal_token_addr"

    info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$erc20_pred \$withdraw_func \$internal_token_addr \$half_eth"
    cast send --private-key $priv_key --rpc-url $blade_rpc $erc20_pred $withdraw_func $internal_token_addr $half_eth | grep status
}

# Withdraw ERC721 contract:
function withdraw_erc721 {
    info "Withdrawing ERC721 contract..."
    if [[ $1 == "i" ]]; then
        if [[ $mock_erc721_addr == "" ]]; then
            error "Internal mock ERC721 contract not created"
            return
        fi


        external_token_addr=$(cast call $erc721_mint_pred --rpc-url $blade_rpc $src2dest $mock_erc721_addr)    
        success "External token address: $external_token_addr"

        info "RUN: cast send --private-key \$priv_key --rpc-url \$geth_rpc \$erc721_mint_pred \$withdraw_func \$external_token_addr \$nft_token_id"
        cast send --private-key $priv_key --rpc-url $geth_rpc $erc721_mint_pred $withdraw_func $external_token_addr $nft_token_id | grep status
        return
    fi

    if [[ $ext_mock_erc721_addr == "" ]]; then
        error "External mock ERC721 contract not created"
        return
    fi


    external_token_addr=$(cast call $ext_erc721_pred --rpc-url $geth_rpc $src2dest $ext_mock_erc721_addr)    
    success "External token address: $external_token_addr"

    info "RUN: cast send --private-key \$priv_key --rpc-url \$blade_rpc \$erc721_pred \$withdraw_func \$external_token_addr \$nft_token_id"
    cast send --private-key $priv_key --rpc-url $blade_rpc $erc721_pred $withdraw_func $external_token_addr $nft_token_id | grep status
}

function native_balance {
    info "Checking native balance..."
    
    if [[ $1 != "e" ]]; then
        info "RUN: cast balance --rpc-url \$blade_rpc \$pub_key"
        cast balance --rpc-url $blade_rpc $pub_key
        return
    fi
    
    info "RUN: cast balance --rpc-url \$geth_rpc \$pub_key"
    cast balance --rpc-url $geth_rpc $pub_key
}

function mock {
    if [[ $1 == "erc20" ]]; then
        create_mock_erc20 $2
    elif [[ $1 == "erc721" ]]; then
        create_mock_erc721 $2
    else
        error "Invalid contract type"
    fi
}

function approve {
    if [[ $1 == "erc20" ]]; then
        approve_erc20 $2
    elif [[ $1 == "erc721" ]]; then
        approve_erc721 $2
    else
        error "Invalid contract type"
    fi
}

function deposit {
    if [[ $1 == "erc20" ]]; then
        deposit_erc20 $2
    elif [[ $1 == "erc721" ]]; then
        deposit_erc721 $2
    else
        error "Invalid contract type"
    fi
}

function check_balance {
    if [[ $1 == "erc20" ]]; then
        check_balance_erc20 $2
    elif [[ $1 == "erc721" ]]; then
        check_balance_erc721 $2
    else
        error "Invalid contract type"
    fi
}

function check_balance_local {
    if [[ $1 == "erc20" ]]; then
        check_balance_local_erc20 $2
    elif [[ $1 == "erc721" ]]; then
        check_balance_local_erc721 $2
    else
        error "Invalid contract type"
    fi
}


function withdraw {
    if [[ $1 == "erc20" ]]; then
        withdraw_erc20 $2
    elif [[ $1 == "erc721" ]]; then
        withdraw_erc721 $2
    else
        error "Invalid contract type"
    fi
}

function print_logs {
    bn=$(cast block-number --rpc-url $blade_rpc)
    success "Block number (BLADE): $bn"
}

while true; do
    info "Options:"
    info "1. Mock"
    info "2. Approve"
    info "3. Deposit"
    info "4. Withdraw"
    info "5. Check balance"
    info "6. Check balance ERC20/ERC721 local"
    info "7. Balance native"
    info "8. Addresses"
    info "9. Block number (BLADE)"
    info "0. Exit"

    read option
    contract_type="erc20"

    if [[ $option < 0 || $option > 9 ]]; then
        info "RUN: $option"
        eval "$option"
        continue
    fi

    if [[ $option > 0 && $option < 7 ]]; then
        info "Enter contract type (1. erc20, 2. erc721):"
        read type

        if [[ $type == "1" ]]; then
            contract_type="erc20"
        elif [[ $type == "2" ]]; then
            contract_type="erc721"
        else
            error "Invalid contract type"
            exit 1
        fi
    fi

    if [[ $option > 0 && $option < 8 ]]; then
        info "Enter (i for i2e, e for e2i):"
        read direction

        if [[ $direction == 1 ]]; then
            direction="i"
        elif [[ $direction == 2 ]]; then
            direction="e"
        fi
    fi

    case $option in
        1)
            mock $contract_type $direction
            ;;
        2)
            approve $contract_type $direction
            ;;
        3)
            deposit $contract_type $direction
            ;;
        4)
            withdraw $contract_type $direction
            ;;
        5)
            check_balance $contract_type $direction
            ;;
        6)
            check_balance_local $contract_type $direction
            ;;
        7)
            native_balance $direction
            ;;
        8)
            addresses 
            ;;
        9)
            print_logs
            ;;
        0)
            exit 0;;
        *)
            echo "Invalid option"
            exit 1
    esac

    echo
    success "Done"
    echo
done