---
name: Nightly Testnet
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  blade_testnet:
    name: Blade Testnet
    uses: ./.github/workflows/availability-tests.yml
    with:
      environment: Blade Testnet
      rpc_url: https://rpc.testnet.ethernal.work
      fund_amount: "3"
      london: true
      notification: true
    secrets:
      PREMINED_PRIVATE_KEY: ${{ secrets.FAUCET_PRIVATE_KEY }}
      ACCOUNT_PRIVATE_KEY: ${{ secrets.ACCOUNT_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  pink_panda_testnet:
    name: Pink Panda Testnet
    uses: ./.github/workflows/availability-tests.yml
    with:
      environment: Pink Panda Testnet
      rpc_url: https://blockchain-rpc.pinkpanda.network
      fund_amount: "3"
      london: true
      notification: true
    secrets:
      PREMINED_PRIVATE_KEY: ${{ secrets.LOADTEST_PRIVATE_KEY }}
      ACCOUNT_PRIVATE_KEY: ${{ secrets.ACCOUNT_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  sanity_check_tests:
    name: Sanity Check Tests
    uses: ./.github/workflows/sanity-check-testnet.yml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
  load_test_eoa:
    name: Load Test EOA
    uses: ./.github/workflows/load-test-testnet.yml
    needs: [sanity_check_tests]
    with:
      type: EOA
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "15m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      notification: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  load_test_erc20:
    name: Load Test ERC20
    uses: ./.github/workflows/load-test-testnet.yml
    needs: [sanity_check_tests, load_test_eoa]
    with:
      type: ERC20
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "20m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      notification: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  load_test_erc721:
    name: Load Test ERC721
    uses: ./.github/workflows/load-test-testnet.yml
    needs: [sanity_check_tests, load_test_eoa, load_test_erc20]
    with:
      type: ERC721
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "55m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      notification: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  load_test_mixed:
    name: Load Test MIXED
    uses: ./.github/workflows/load-test-testnet.yml
    needs:
      [sanity_check_tests, load_test_eoa, load_test_erc20, load_test_erc721]
    with:
      type: MIXED
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "30m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      notification: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  load_test_perf:
    name: Load Test PERFORMANCE CONTRACT
    uses: ./.github/workflows/load-test-testnet.yml
    needs:
      [
        sanity_check_tests,
        load_test_eoa,
        load_test_erc20,
        load_test_erc721,
        load_test_mixed,
      ]
    with:
      type: PERF-CONTRACT
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "55m0s"
      wait_txpool: true
      receipts_timeout: "5m0s"
      batch_size: "10000"
      notification: false
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_sanity_check:
    name: Nightly Notification
    uses: ./.github/workflows/notification-testnet.yml
    needs: [sanity_check_tests]
    if: success() || failure()
    with:
      sanity_check_tests_output: ${{ needs.sanity_check_tests.outputs.sanity_check_tests_output }}
      stake_test_output: ${{ needs.sanity_check_tests.outputs.stake_test_output }}
      unstake_test_output: ${{ needs.sanity_check_tests.outputs.unstake_test_output }}
      register_validator_test_output: ${{ needs.sanity_check_tests.outputs.register_validator_test_output }}
      withdraw_rewards_test_output: ${{ needs.sanity_check_tests.outputs.withdraw_rewards_test_output }}
      unstake_all_test_output: ${{ needs.sanity_check_tests.outputs.unstake_all_test_output }}
      results_artifact_id: ${{ needs.sanity_check_tests.outputs.results_artifact_id }}
    secrets:
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_eoa:
    name: Load Test EOA Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [load_test_eoa, notification_sanity_check]
    if: (always() && needs.load_test_eoa.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: EOA
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "15m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      total_time: ${{ needs.load_test_eoa.outputs.total_time }}
      total_txs: ${{ needs.load_test_eoa.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_eoa.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_eoa.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_eoa.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_eoa.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_eoa.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_eoa.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_eoa.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_eoa.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_eoa.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_eoa.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_erc20:
    name: Load Test ERC20 Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs:
      [load_test_erc20, notification_sanity_check, notification_load_test_eoa]
    if: (always() && needs.load_test_erc20.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: ERC20
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "20m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      total_time: ${{ needs.load_test_erc20.outputs.total_time }}
      total_txs: ${{ needs.load_test_erc20.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_erc20.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_erc20.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_erc20.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_erc20.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_erc20.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_erc20.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_erc20.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_erc20.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_erc20.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_erc20.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_erc721:
    name: Load Test ERC721 Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs:
      [
        load_test_erc721,
        notification_sanity_check,
        notification_load_test_eoa,
        notification_load_test_erc20,
      ]
    if: (always() && needs.load_test_erc721.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: ERC721
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "55m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      total_time: ${{ needs.load_test_erc721.outputs.total_time }}
      total_txs: ${{ needs.load_test_erc721.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_erc721.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_erc721.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_erc721.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_erc721.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_erc721.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_erc721.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_erc721.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_erc721.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_erc721.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_erc721.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_mixed:
    name: Load Test MIXED Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs:
      [
        load_test_mixed,
        notification_sanity_check,
        notification_load_test_eoa,
        notification_load_test_erc20,
        notification_load_test_erc721,
      ]
    if: (always() && needs.load_test_mixed.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: MIXED
      dynamic: true
      vus: "100"
      txs_per_user: "10000"
      txpool_timeout: "30m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "10000"
      total_time: ${{ needs.load_test_mixed.outputs.total_time }}
      total_txs: ${{ needs.load_test_mixed.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_mixed.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_mixed.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_mixed.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_mixed.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_mixed.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_mixed.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_mixed.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_mixed.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_mixed.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_mixed.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
