---
name: Nightly Testnet
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  availability_tests:
    name: Availability Tests
    uses: ./.github/workflows/availability-tests.yml
    with:
      rpc_url: ${{ vars.TESTNET_JSONRPC_URL }}
      fund_amount: "3"
      london: true
    secrets:
      PREMINED_PRIVATE_KEY: ${{ secrets.FAUCET_PRIVATE_KEY }}
      ACCOUNT_PRIVATE_KEY: ${{ secrets.ACCOUNT_PRIVATE_KEY }}
  sanity_check_tests:
    name: Sanity Check Test
    uses: ./.github/workflows/sanity-check-test.yml
    needs: availability_tests
    with:
      environment: testnet
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
  load_test_perf:
    name: Load Test PERFORMANCE CONTRACT
    uses: ./.github/workflows/load-test.yml
    needs: [availability_tests, sanity_check_tests]
    with:
      environment: testnet
      type: PERF-CONTRACT
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "30m0s"
      wait_txpool: true
      receipts_timeout: "5m0s"
      batch_size: "1000"
      notification: false
      monitoring: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  load_test_eoa:
    name: Load Test EOA
    uses: ./.github/workflows/load-test.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf]
    with:
      environment: testnet
      type: EOA
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "15m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      notification: false
      monitoring: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  load_test_erc20:
    name: Load Test ERC20
    uses: ./.github/workflows/load-test.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf, load_test_eoa]
    with:
      environment: testnet
      type: ERC20
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "20m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      notification: false
      monitoring: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  load_test_erc721:
    name: Load Test ERC721
    uses: ./.github/workflows/load-test.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf, load_test_eoa, load_test_erc20]
    with:
      environment: testnet
      type: ERC721
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "55m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      notification: false
      monitoring: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  load_test_mixed:
    name: Load Test MIXED
    uses: ./.github/workflows/load-test.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf, load_test_eoa, load_test_erc20, load_test_erc721]
    with:
      environment: testnet
      type: MIXED
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "30m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      notification: false
      monitoring: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  load_test_erc1155:
    name: Load Test ERC1155
    uses: ./.github/workflows/load-test.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf, load_test_eoa, load_test_erc20, load_test_erc721, load_test_mixed]
    with:
      environment: testnet
      type: ERC1155
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "50m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      notification: false
      monitoring: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_AMI_ID: ${{ secrets.AWS_LOADTESTRUNNER_AMI_ID }}
      AWS_LOADTESTRUNNER_SUBNET_ID: ${{ secrets.AWS_LOADTESTRUNNER_SUBNET_ID }}
      AWS_LOADTESTRUNNER_SG_ID: ${{ secrets.AWS_LOADTESTRUNNER_SG_ID }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  sync_fullnode_test:
    name: Sync Fullnode Test
    uses: ./.github/workflows/sync-test.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf, load_test_eoa, load_test_erc20, load_test_erc721, load_test_mixed, load_test_erc1155]
    with:
      environment: testnet
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
      MONITORING_SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
  testnet_notification:
    name: Testnet Nightly Notification
    uses: ./.github/workflows/notification-testnet.yml
    needs: [availability_tests, sanity_check_tests, load_test_perf, load_test_eoa, load_test_erc20, load_test_erc721, load_test_mixed, load_test_erc1155, sync_fullnode_test]
    if: success() || failure()
    with:
      availability_test_status: ${{ needs.availability_tests.outputs.availability_test_status }}
      sanity_check_tests_output: ${{ needs.sanity_check_tests.outputs.sanity_check_tests_output }}
      stake_test_output: ${{ needs.sanity_check_tests.outputs.stake_test_output }}
      unstake_test_output: ${{ needs.sanity_check_tests.outputs.unstake_test_output }}
      register_validator_test_output: ${{ needs.sanity_check_tests.outputs.register_validator_test_output }}
      withdraw_rewards_test_output: ${{ needs.sanity_check_tests.outputs.withdraw_rewards_test_output }}
      unstake_all_test_output: ${{ needs.sanity_check_tests.outputs.unstake_all_test_output }}
      results_artifact_id: ${{ needs.sanity_check_tests.outputs.results_artifact_id }}
      load_test_perf_output: ${{ needs.load_test_perf.outputs.load_test_output }}
      load_test_perf_txpool_pending_output: ${{ needs.load_test_perf.outputs.txpool_pending }}
      load_test_perf_txpool_queued_output: ${{ needs.load_test_perf.outputs.txpool_queued }}
      load_test_eoa_output: ${{ needs.load_test_eoa.outputs.load_test_output }}
      load_test_eoa_txpool_pending_output: ${{ needs.load_test_eoa.outputs.txpool_pending }}
      load_test_eoa_txpool_queued_output: ${{ needs.load_test_eoa.outputs.txpool_queued }}
      load_test_erc20_output: ${{ needs.load_test_erc20.outputs.load_test_output }}
      load_test_erc20_txpool_pending_output: ${{ needs.load_test_erc20.outputs.txpool_pending }}
      load_test_erc20_txpool_queued_output: ${{ needs.load_test_erc20.outputs.txpool_queued }}
      load_test_erc721_output: ${{ needs.load_test_erc721.outputs.load_test_output }}
      load_test_erc721_txpool_pending_output: ${{ needs.load_test_erc721.outputs.txpool_pending }}
      load_test_erc721_txpool_queued_output: ${{ needs.load_test_erc721.outputs.txpool_queued }}
      load_test_mixed_output: ${{ needs.load_test_mixed.outputs.load_test_output }}
      load_test_mixed_txpool_pending_output: ${{ needs.load_test_mixed.outputs.txpool_pending }}
      load_test_mixed_txpool_queued_output: ${{ needs.load_test_mixed.outputs.txpool_queued }}
      load_test_erc1155_output: ${{ needs.load_test_erc1155.outputs.load_test_output }}
      load_test_erc1155_txpool_pending_output: ${{ needs.load_test_erc1155.outputs.txpool_pending }}
      load_test_erc1155_txpool_queued_output: ${{ needs.load_test_erc1155.outputs.txpool_queued }}
      sync_fullnode_test_output: ${{ needs.sync_fullnode_test.outputs.ansible_output }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_perf:
    name: Load Test PERFORMANCE CONTRACT Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [testnet_notification, load_test_perf]
    if: (always() && needs.load_test_perf.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: PERF-CONTRACT
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "30m0s"
      wait_txpool: true
      receipts_timeout: "5m0s"
      batch_size: "1000"
      total_time: ${{ needs.load_test_perf.outputs.total_time }}
      total_txs: ${{ needs.load_test_perf.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_perf.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_perf.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_perf.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_perf.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_perf.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_perf.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_perf.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_perf.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_perf.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_perf.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_eoa:
    name: Load Test EOA Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [load_test_eoa, testnet_notification, notification_load_test_perf]
    if: (always() && needs.load_test_eoa.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: EOA
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "15m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      total_time: ${{ needs.load_test_eoa.outputs.total_time }}
      total_txs: ${{ needs.load_test_eoa.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_eoa.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_eoa.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_eoa.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_eoa.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_eoa.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_eoa.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_eoa.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_eoa.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_eoa.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_eoa.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_erc20:
    name: Load Test ERC20 Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [load_test_erc20, testnet_notification, notification_load_test_perf, notification_load_test_eoa]
    if: (always() && needs.load_test_erc20.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: ERC20
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "20m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      total_time: ${{ needs.load_test_erc20.outputs.total_time }}
      total_txs: ${{ needs.load_test_erc20.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_erc20.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_erc20.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_erc20.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_erc20.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_erc20.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_erc20.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_erc20.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_erc20.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_erc20.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_erc20.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_erc721:
    name: Load Test ERC721 Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [load_test_erc721, testnet_notification, notification_load_test_perf, notification_load_test_eoa, notification_load_test_erc20]
    if: (always() && needs.load_test_erc721.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: ERC721
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "55m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      total_time: ${{ needs.load_test_erc721.outputs.total_time }}
      total_txs: ${{ needs.load_test_erc721.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_erc721.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_erc721.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_erc721.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_erc721.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_erc721.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_erc721.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_erc721.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_erc721.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_erc721.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_erc721.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_mixed:
    name: Load Test MIXED Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [load_test_mixed, testnet_notification, notification_load_test_perf, notification_load_test_eoa, notification_load_test_erc20, notification_load_test_erc721]
    if: (always() && needs.load_test_mixed.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: MIXED
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "30m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      total_time: ${{ needs.load_test_mixed.outputs.total_time }}
      total_txs: ${{ needs.load_test_mixed.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_mixed.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_mixed.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_mixed.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_mixed.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_mixed.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_mixed.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_mixed.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_mixed.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_mixed.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_mixed.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  notification_load_test_erc1155:
    name: Load Test ERC1155 Notification
    uses: ./.github/workflows/notification-load-test.yml
    needs: [load_test_erc1155, testnet_notification, notification_load_test_perf, notification_load_test_eoa, notification_load_test_erc20, notification_load_test_erc721, notification_load_test_mixed]
    if: (always() && needs.load_test_erc1155.outputs.load_test_output == 'true')
    with:
      environment: testnet
      type: ERC1155
      dynamic: true
      vus: "100"
      txs_per_user: "1000"
      txpool_timeout: "50m0s"
      wait_txpool: true
      receipts_timeout: "2m0s"
      batch_size: "1000"
      total_time: ${{ needs.load_test_erc1155.outputs.total_time }}
      total_txs: ${{ needs.load_test_erc1155.outputs.total_txs }}
      total_blocks: ${{ needs.load_test_erc1155.outputs.total_blocks }}
      avg_txs_per_second: ${{ needs.load_test_erc1155.outputs.avg_txs_per_second }}
      max_txs_per_second: ${{ needs.load_test_erc1155.outputs.max_txs_per_second }}
      total_gas_used: ${{ needs.load_test_erc1155.outputs.total_gas_used }}
      avg_gas_per_tx: ${{ needs.load_test_erc1155.outputs.avg_gas_per_tx }}
      avg_gas_utilization: ${{ needs.load_test_erc1155.outputs.avg_gas_utilization }}
      max_gas_utilization: ${{ needs.load_test_erc1155.outputs.max_gas_utilization }}
      txpool_pending: ${{ needs.load_test_erc1155.outputs.txpool_pending }}
      txpool_queued: ${{ needs.load_test_erc1155.outputs.txpool_queued }}
      results_artifact_id: ${{ needs.load_test_erc1155.outputs.results_artifact_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
