---
name: Notification
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment:
        description: The environment to run against
        type: string
        required: true
      description:
        description: Description
        type: string
        required: true
    secrets:
      MONITORING_SLACK_WEBHOOK_URL:
        required: true

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MONITORING_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ inputs.description }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Environment: *${{ inputs.environment }}*"
                    }
                  ]
                }
              ]
            }
