---
name: Testnet Notification
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      bat_network:
        type: string
        required: true
      bat_availability_test_status:
        type: string
        required: true
      pp_network:
        type: string
        required: true
      pp_availability_test_status:
        type: string
        required: true
      sanity_check_tests_output:
        description: Sanity Check Tests output
        type: string
        required: true
      stake_test_output:
        description: Stake Test output
        type: string
        required: true
      unstake_test_output:
        description: Unstake Test output
        type: string
        required: true
      register_validator_test_output:
        description: Register Validator Test output
        type: string
        required: true
      withdraw_rewards_test_output:
        description: Withdraw Rewards Test output
        type: string
        required: true
      unstake_all_test_output:
        description: Unstake All Test output
        type: string
        required: true
      results_artifact_id:
        type: string
        required: true
      load_test_perf_output:
        description: Load Test PERFORMANCE CONTRACT output
        type: string
        required: true
      load_test_perf_txpool_pending_output:
        description: Load Test PERFORMANCE CONTRACT txpool pending output
        type: string
        required: true
      load_test_perf_txpool_queued_output:
        description: Load Test PERFORMANCE CONTRACT txpool queued output
        type: string
        required: true
      load_test_eoa_output:
        description: Load Test EOA output
        type: string
        required: true
      load_test_eoa_txpool_pending_output:
        description: Load Test EOA txpool pending output
        type: string
        required: true
      load_test_eoa_txpool_queued_output:
        description: Load Test EOA txpool queued output
        type: string
        required: true
      load_test_erc20_output:
        description: Load Test ERC20 output
        type: string
        required: true
      load_test_erc20_txpool_pending_output:
        description: Load Test ERC20 txpool pending output
        type: string
        required: true
      load_test_erc20_txpool_queued_output:
        description: Load Test ERC20 txpool queued output
        type: string
        required: true
      load_test_erc721_output:
        description: Load Test ERC721 output
        type: string
        required: true
      load_test_erc721_txpool_pending_output:
        description: Load Test ERC721 txpool pending output
        type: string
        required: true
      load_test_erc721_txpool_queued_output:
        description: Load Test ERC721 txpool queued output
        type: string
        required: true
      load_test_mixed_output:
        description: Load Test MIXED output
        type: string
        required: true
      load_test_mixed_txpool_pending_output:
        description: Load Test MIXED txpool pending output
        type: string
        required: true
      load_test_mixed_txpool_queued_output:
        description: Load Test MIXED txpool queued output
        type: string
        required: true
      load_test_erc1155_output:
        description: Load Test ERC1155 output
        type: string
        required: true
      load_test_erc1155_txpool_pending_output:
        description: Load Test ERC1155 txpool pending output
        type: string
        required: true
      load_test_erc1155_txpool_queued_output:
        description: Load Test ERC1155 txpool queued output
        type: string
        required: true
    secrets:
      AWS_S3_BLADE_BUCKET:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    environment: testnet
    steps:
      - name: Short SHA
        id: short_sha
        run: echo "value=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          succeed_bnt: "primary"
          failed_bnt: "danger"
          succeed_job: ":green:"
          failed_job: ":red:"
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Nightly Testnet"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Workflow Run"
                      },
                      "style": "${{ inputs.bat_availability_test_status == 'true' && inputs.pp_availability_test_status == 'true' && inputs.sanity_check_tests_output == 'true' && inputs.load_test_perf_output == 'true' && inputs.load_test_perf_txpool_pending_output == '0' && inputs.load_test_perf_txpool_queued_output == '0' && inputs.load_test_eoa_output == 'true' && inputs.load_test_eoa_txpool_pending_output == '0' && inputs.load_test_eoa_txpool_queued_output == '0' && inputs.load_test_erc20_output == 'true' && inputs.load_test_erc20_txpool_pending_output == '0' && inputs.load_test_erc20_txpool_queued_output == '0' && inputs.load_test_erc721_output == 'true' && inputs.load_test_erc721_txpool_pending_output == '0' && inputs.load_test_erc721_txpool_queued_output == '0' && inputs.load_test_mixed_output == 'true' && inputs.load_test_mixed_txpool_pending_output == '0' && inputs.load_test_mixed_txpool_queued_output == '0' && inputs.load_test_erc1155_output == 'true' && inputs.load_test_erc1155_txpool_pending_output == '0' && inputs.load_test_erc1155_txpool_queued_output == '0' && env.succeed_bnt || env.failed_bnt }}",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Sanity Check Results"
                      },
                      "style": "${{ inputs.sanity_check_tests_output == 'true' && env.succeed_bnt || env.failed_bnt }}",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ inputs.results_artifact_id }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.bat_availability_test_status == 'true' && env.succeed_job || env.failed_job }} *${{ inputs.bat_network }} Availability Tests*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.pp_availability_test_status == 'true' && env.succeed_job || env.failed_job }} *${{ inputs.pp_network }} Availability Tests*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.stake_test_output == 'PASSED' && env.succeed_job || env.failed_job }} *Stake Test*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.unstake_test_output == 'PASSED' && env.succeed_job || env.failed_job }} *Unstake Test*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.register_validator_test_output == 'PASSED' && env.succeed_job || env.failed_job }} *Register Validator Test*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.withdraw_rewards_test_output == 'PASSED' && env.succeed_job || env.failed_job }} *Withdraw Rewards Test*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.unstake_all_test_output == 'PASSED' && env.succeed_job || env.failed_job }} *Unstake All Test*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.load_test_perf_output == 'true' && inputs.load_test_perf_txpool_pending_output == '0' && inputs.load_test_perf_txpool_queued_output == '0' && env.succeed_job || env.failed_job }} *Load Test PERF. CONTRACT*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.load_test_eoa_output == 'true' && inputs.load_test_eoa_txpool_pending_output == '0' && inputs.load_test_eoa_txpool_queued_output == '0' && env.succeed_job || env.failed_job }} *Load Test EOA*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.load_test_erc20_output == 'true' && inputs.load_test_erc20_txpool_pending_output == '0' && inputs.load_test_erc20_txpool_queued_output == '0' && env.succeed_job || env.failed_job }} *Load Test ERC20*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.load_test_erc721_output == 'true' && inputs.load_test_erc721_txpool_pending_output == '0' && inputs.load_test_erc721_txpool_queued_output == '0' && env.succeed_job || env.failed_job }} *Load Test ERC721*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.load_test_mixed_output == 'true' && inputs.load_test_mixed_txpool_pending_output == '0' && inputs.load_test_mixed_txpool_queued_output == '0' && env.succeed_job || env.failed_job }} *Load Test MIXED*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ inputs.load_test_erc1155_output == 'true' && inputs.load_test_erc1155_txpool_pending_output == '0' && inputs.load_test_erc1155_txpool_queued_output == '0' && env.succeed_job || env.failed_job }} *Load Test ERC1155*"
                    }
                  ]
                }
              ]
            }
