---
name: Sanity Check Testnet - Nightly
on: # yamllint disable-line rule:truthy
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sanity_check_tests:
    name: Sanity Check Tests
    uses: ./.github/workflows/sanity-check-testnet.yml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      AWS_LOADTESTRUNNER_MNEMONIC: ${{ secrets.AWS_LOADTESTRUNNER_MNEMONIC }}
  notification_nightly:
    name: Nightly Notification
    uses: ./.github/workflows/notification-sanity-check-testnet.yml
    needs: [sanity_check_tests]
    if: success() || failure()
    with:
      environment: testnet
      sanity_check_tests_output: ${{ needs.sanity_check_tests.outputs.sanity_check_tests_output }}
      stake_test_output: ${{ needs.sanity_check_tests.outputs.stake_test_output }}
      unstake_test_output: ${{ needs.sanity_check_tests.outputs.unstake_test_output }}
      register_validator_test_output: ${{ needs.sanity_check_tests.outputs.register_validator_test_output }}
      withdraw_rewards_test_output: ${{ needs.sanity_check_tests.outputs.withdraw_rewards_test_output }}
      unstake_all_test_output: ${{ needs.sanity_check_tests.outputs.unstake_all_test_output}}

    secrets:
      AWS_S3_BLADE_BUCKET: ${{ secrets.AWS_S3_BLADE_BUCKET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
